
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action DellaAction;
	private global::Gtk.Action DellaAction1;
	private global::Gtk.Action BearbeitenAction;
	private global::Gtk.Action AnsichtAction;
	private global::Gtk.Action HilfeAction;
	private global::Gtk.VBox mainVBox;
	private global::Gtk.MenuBar mainMenuBar;
	private global::Gtk.ScrolledWindow scrollArea;
	private global::Gtk.Statusbar statusbar;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.DellaAction = new global::Gtk.Action ("DellaAction", global::Mono.Unix.Catalog.GetString ("Della"), null, null);
		this.DellaAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Della");
		w1.Add (this.DellaAction, null);
		this.DellaAction1 = new global::Gtk.Action ("DellaAction1", global::Mono.Unix.Catalog.GetString ("Della"), null, null);
		this.DellaAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Della");
		w1.Add (this.DellaAction1, null);
		this.BearbeitenAction = new global::Gtk.Action ("BearbeitenAction", global::Mono.Unix.Catalog.GetString ("Bearbeiten"), null, null);
		this.BearbeitenAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Bearbeiten");
		w1.Add (this.BearbeitenAction, null);
		this.AnsichtAction = new global::Gtk.Action ("AnsichtAction", global::Mono.Unix.Catalog.GetString ("Ansicht"), null, null);
		this.AnsichtAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Ansicht");
		w1.Add (this.AnsichtAction, null);
		this.HilfeAction = new global::Gtk.Action ("HilfeAction", global::Mono.Unix.Catalog.GetString ("Hilfe"), null, null);
		this.HilfeAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Hilfe");
		w1.Add (this.HilfeAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.AllowShrink = true;
		this.Gravity = ((global::Gdk.Gravity)(5));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.mainVBox = new global::Gtk.VBox ();
		this.mainVBox.Name = "mainVBox";
		this.mainVBox.Spacing = 6;
		// Container child mainVBox.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='mainMenuBar'><menu name='DellaAction1' action='DellaAction1'/><menu name='BearbeitenAction' action='BearbeitenAction'/><menu name='AnsichtAction' action='AnsichtAction'/><menu name='HilfeAction' action='HilfeAction'/></menubar></ui>");
		this.mainMenuBar = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/mainMenuBar")));
		this.mainMenuBar.Name = "mainMenuBar";
		this.mainVBox.Add (this.mainMenuBar);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.mainVBox [this.mainMenuBar]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child mainVBox.Gtk.Box+BoxChild
		this.scrollArea = new global::Gtk.ScrolledWindow ();
		this.scrollArea.CanFocus = true;
		this.scrollArea.Name = "scrollArea";
		this.scrollArea.ShadowType = ((global::Gtk.ShadowType)(1));
		this.mainVBox.Add (this.scrollArea);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.mainVBox [this.scrollArea]));
		w3.Position = 1;
		// Container child mainVBox.Gtk.Box+BoxChild
		this.statusbar = new global::Gtk.Statusbar ();
		this.statusbar.Name = "statusbar";
		this.statusbar.Spacing = 6;
		this.mainVBox.Add (this.statusbar);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.mainVBox [this.statusbar]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		this.Add (this.mainVBox);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 612;
		this.DefaultHeight = 400;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
